---
apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"acp-deny-all","namespace":"postcodeinfo-dev"},"spec":{"podSelector":{}}}
      generation: 1
      name: acp-deny-all
      namespace: postcodeinfo-dev
      resourceVersion: "198538583"
      selfLink: /apis/networking.k8s.io/v1/namespaces/postcodeinfo-dev/networkpolicies/acp-deny-all
      uid: 0454b2ca-1f14-11e9-a558-0263dbcc0fba
    spec:
      podSelector: {}
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      generation: 1
      name: pci-allow-ingress
      namespace: postcodeinfo-dev
      resourceVersion: "200084032"
      selfLink: /apis/networking.k8s.io/v1/namespaces/postcodeinfo-dev/networkpolicies/pci-allow-ingress
      uid: f351104e-20bf-11e9-a558-0263dbcc0fba
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  name: ingress-internal
          ports:
            - port: 10080
              protocol: TCP
            - port: 10443
              protocol: TCP
      podSelector:
        matchLabels:
          name: pci
      policyTypes:
        - Ingress
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
