---
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: acp-deny-all
    namespace: postcodeinfo-dev
  spec:
    podSelector: {}
    policyTypes:
      - Ingress

- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: pci-allow-ingress
    namespace: postcodeinfo-dev
  spec:
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                name: ingress-internal
        ports:
          - port: 10080
            protocol: TCP
          - port: 10443
            protocol: TCP
    podSelector:
      matchLabels:
        name: pci
    policyTypes:
      - Ingress
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
