---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pci
  name: pci
  namespace: postcodeinfo-dev
spec:
  type: ClusterIP
  selector:
    name: pci
  ports:
    - name: http
      port: 10080
      protocol: TCP
      targetPort: 10080
    - name: https
      port: 10443
      protocol: TCP
      targetPort: 10443
  sessionAffinity: None
status:
  loadBalancer: {}
