---
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: pci
        role: service
      name: pci
      namespace: postcodeinfo
      resourceVersion: "139155693"
    spec:
      clusterIP: 10.10.5.30
      ports:
        - name: http
          port: 10080
          protocol: TCP
          targetPort: 10080
        - name: https
          port: 10443
          protocol: TCP
          targetPort: 10443
      selector:
        name: pci
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
