apiVersion: v1
kind: ConfigMap
metadata:
  name: pci-configmap
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    name: pci
data:
  ENVIRONMENT: "DEV"
  COMMIT_SHA: {{ .DRONE_COMMIT_SHA }}
  GA_ID: " "
  NODE_ENV: "development"
  TEMPLATE_QUERY: " "
  TEMPLATE_FEEDBACK: " "
