---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    downscaler/uptime: Mon-Fri 07:00-21:00 Europe/London
  name: pci
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pci
  template:
    metadata:
      labels:
        name: pci
        app: pci
        service: pci
    spec:
      containers:
        - name: pci
          image: quay.io/ukhomeofficedigital/postcodeinfo:${DRONE_COMMIT_SHA}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: pci-configmap
          resources:
            requests:
              cpu: "20m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"
          volumeMounts:
            - mountPath: /public
              name: public
      volumes:
        - name: public
          emptyDir: {}
        - name: configmap
          configMap:
            name: configmap
